name: ci
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            6.0.x
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release -p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }} --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --no-restore
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: nugets\*.nupkg
      - name: PushNuget
        run: dotnet nuget push nugets\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
