name: test
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Build
        run: dotnet build -c Release -p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }}
      - name: Test
        run: dotnet test -c Release --no-build --no-restore
